# Generated by Django 5.0.4 on 2024-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='link_to_video',
            field=models.CharField(default='', max_length=200),
        ),
    ]
