# Generated by Django 5.0.4 on 2024-06-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
