# Generated by Django 5.0.4 on 2024-06-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_weight',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_weight',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_weight',
            field=models.FloatField(default=50),
        ),
    ]
