# Generated by Django 5.0.4 on 2024-06-13 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progress', '0003_historicalgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicalgoal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
