# Generated by Django 5.0.4 on 2024-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progress', '0007_userachievement_claimed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rule',
            field=models.TextField(default='', help_text='Python code to check if the user meets the condition'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
