# Generated by Django 5.0.4 on 2024-06-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progress', '0008_achievement_rule_userachievement_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='rule',
            field=models.TextField(default='', help_text='Запрос на питоне для определения выполнения задания\n    Будем считать, что оно возращает кортеж из двух объектов. Текущего количества условных единиц и необходимого'),
        ),
    ]
