# Generated by Django 5.0.4 on 2024-06-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progress', '0009_alter_achievement_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='needed_for_reach',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
