# Generated by Django 5.0.4 on 2024-06-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progress', '0010_achievement_needed_for_reach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_work', 'В процессе'), ('Done', 'Завершена'), ('Failed', 'Провалена')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalgoal',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_work', 'В процессе'), ('Done', 'Завершена'), ('Failed', 'Провалена')], default='New', max_length=20),
        ),
    ]
