# Generated by Django 5.0.4 on 2024-06-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progress', '0011_alter_goal_status_alter_historicalgoal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.JSONField(default=dict)),
            ],
        ),
    ]
