# Generated by Django 5.0.4 on 2024-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_exercise_link_to_video'),
        ('Colories', '0008_alter_selection_category'),
        ('Expertise', '0004_alter_experttimetable_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercourse',
            name='exercises',
            field=models.ManyToManyField(to='Activity.exercise'),
        ),
        migrations.AddField(
            model_name='mastercourse',
            name='selections',
            field=models.ManyToManyField(to='Colories.selection'),
        ),
    ]
