# Generated by Django 5.0.4 on 2024-06-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCaloryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('goal', models.CharField(choices=[('lose', 'Lose weight'), ('gain', 'Gain weight'), ('maintain', 'Maintain weight')], max_length=10)),
                ('target_weight', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (light exercise/sports 1-3 days/week)'), ('moderate', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('active', 'Very active (hard exercise/sports 6-7 days a week)'), ('super_active', 'Super active (very hard exercise/sports & physical job)')], max_length=20)),
                ('target_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calory_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
