# Generated by Django 5.0.4 on 2024-06-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_expertprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertprofile',
            old_name='price_per_hout',
            new_name='price_per_hour',
        ),
    ]
