# Generated by Django 5.0.4 on 2024-06-09 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measurement_unit', models.CharField(max_length=20)),
                ('calories_per_unit', models.PositiveIntegerField()),
                ('proteins_per_unit', models.FloatField()),
                ('fats_per_unit', models.FloatField()),
                ('carbohydrates_per_unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_meals', models.PositiveIntegerField(default=0)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('total_proteins', models.FloatField(default=0)),
                ('total_fats', models.FloatField(default=0)),
                ('total_carbohydrates', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.FloatField()),
                ('meal_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Breakfast', 'Завтрак'), ('Dinner', 'Обед'), ('Supper', 'Ужин'), ('Snack', 'Перекус')], default='Новая', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colories.product')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(to='Colories.product')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCaloryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_goal', models.PositiveIntegerField()),
                ('consumed_calories', models.PositiveIntegerField(default=0)),
                ('burned_calories_exercise', models.PositiveIntegerField(default=0)),
                ('burned_calories_sleep', models.PositiveIntegerField(default=0)),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Colories.history')),
                ('recommendations', models.ManyToManyField(to='Colories.selection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calory_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
