# Generated by Django 5.0.4 on 2024-06-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Colories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercaloryprofile',
            name='history',
        ),
    ]
