# Generated by Django 5.0.4 on 2024-06-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Colories', '0002_remove_usercaloryprofile_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCaloryProfile',
        ),
    ]
