# Generated by Django 5.0.6 on 2024-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colories', '0002_delete_usercaloryprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealrecord',
            name='is_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mealrecord',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Завтрак'), ('Dinner', 'Обед'), ('Supper', 'Ужин'), ('Snack', 'Перекус'), ('Water', 'Вода')], default='Новая', max_length=20),
        ),
    ]
