# Generated by Django 5.0.4 on 2024-06-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Colories', '0003_mealrecord_is_water_alter_mealrecord_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrecord',
            name='is_water',
        ),
    ]
