# Generated by Django 5.0.4 on 2024-06-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colories', '0004_remove_mealrecord_is_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='go_to_sleep_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
