# Generated by Django 5.0.4 on 2024-06-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colories', '0005_timetable_go_to_sleep_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='Colories.timetable')),
            ],
            options={
                'unique_together': {('time_table', 'day_of_week', 'start_time')},
            },
        ),
    ]
