# Generated by Django 5.0.4 on 2024-06-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Colories', '0006_trainingsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingSession',
        ),
    ]
